/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//TOTO IMPORTE PARA CRIAR AS FUCIONALIDADES DO VIEW//
package Views;

import Modelo.ModeloFuncionarios;
import javax.swing.JFrame;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import Conexao.ConectaBanco;
import Conexao.ControleFuncionario;


/**
 *
 * @author nykso
 */
//AQUI EU CRIEI CONEXÃO COM BANCO DE DADOS NA NA HORA DE INSERIR OS DADOS NO CAMPO DE TEXTO ELE CAPITURA E SALVA EM UMA VARIAVEL
public class jifcadastro extends javax.swing.JInternalFrame {
    
    ModeloFuncionarios mod = new ModeloFuncionarios();
    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco conex = new ConectaBanco();
    ControleFuncionario control = new ControleFuncionario();
    
    /**
     * Creates new form jifcadastro
     */
    public jifcadastro() {
        initComponents();
        conecta.getConnection();
    }

    
   
       
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        lstFuncionarios = new LinkedList<Funcionarios>();
        jtsalario = new javax.swing.JTextField();
        jbnovo = new javax.swing.JButton();
        jbadicionar = new javax.swing.JButton();
        jtservico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jblimpar = new javax.swing.JButton();
        jbexcluir = new javax.swing.JButton();
        jtqualificacao = new javax.swing.JTextField();
        jtsexo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbsalvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtcargo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        lstFuncionarios = org.jdesktop.observablecollections.ObservableCollections.observableList(lstFuncionarios);

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Funcionarios");
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                formComponentRemoved(evt);
            }
        });
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jtsalario.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.salario}"), jtsalario, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jtsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtsalarioActionPerformed(evt);
            }
        });
        jtsalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtsalarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtsalarioKeyTyped(evt);
            }
        });

        jbnovo.setText("Novo");
        jbnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnovoActionPerformed(evt);
            }
        });

        jbadicionar.setText("Adicionar");
        jbadicionar.setEnabled(false);
        jbadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbadicionarActionPerformed(evt);
            }
        });

        jtservico.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.servico}"), jtservico, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jtservico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtservicoActionPerformed(evt);
            }
        });
        jtservico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtservicoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtservicoKeyTyped(evt);
            }
        });

        jLabel2.setText("Sexo");

        jLabel3.setText("Salario R$");

        jLabel4.setText("Serviço");

        jLabel5.setText("Qualificação ");

        jblimpar.setText("Limpar");
        jblimpar.setEnabled(false);
        jblimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimparActionPerformed(evt);
            }
        });

        jbexcluir.setText("Excluir");
        jbexcluir.setEnabled(false);
        jbexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexcluirActionPerformed(evt);
            }
        });

        jtqualificacao.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.qualificacao}"), jtqualificacao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jtqualificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtqualificacaoActionPerformed(evt);
            }
        });
        jtqualificacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtqualificacaoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtqualificacaoKeyTyped(evt);
            }
        });

        jtsexo.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.sexo}"), jtsexo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jtsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtsexoActionPerformed(evt);
            }
        });
        jtsexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtsexoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtsexoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtsexoKeyTyped(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstFuncionarios, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cargo}"));
        columnBinding.setColumnName("Cargo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sexo}"));
        columnBinding.setColumnName("Sexo");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${servico}"));
        columnBinding.setColumnName("Servico");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${salario}"));
        columnBinding.setColumnName("Salario");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${qualificacao}"));
        columnBinding.setColumnName("Qualificacao");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Informe para Masculino 1 / Feminino 0 ");

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Informe para qualificado 1 / sem qualificação 0");

        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Informe Salário bruto!");

        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Infome anos de contribuição");

        jbsalvar.setText("Salvar");
        jbsalvar.setEnabled(false);
        jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalvarActionPerformed(evt);
            }
        });

        jLabel9.setText("Cargo");

        jtcargo.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cargo}"), jtcargo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jtcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcargoActionPerformed(evt);
            }
        });
        jtcargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtcargoKeyReleased(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Inofrme o nome do funcionario");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salarial.png (3).png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel13.setText("Comparação entre Salários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(jtservico, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 420, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addComponent(jtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel10)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jtqualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jbnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbadicionar)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)))
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtservico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtqualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(57, 57, 57)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbadicionar)
                            .addComponent(jbnovo))
                        .addGap(18, 18, 18)
                        .addComponent(jbsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbexcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jblimpar)
                        .addGap(33, 33, 33))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtsalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtsalarioActionPerformed

    private void jtservicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtservicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtservicoActionPerformed
            // AQUI CREIE UM BOTÃO ADICIONAR PARA PODER INSERIR OS DADOS NA TABELA "Jtable1" capiturando os gets e sets da clase funcionarios -1 é para começar sem nenhuma linha//
    private void jbadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbadicionarActionPerformed
        // TODO add your handling code here:
        Funcionarios f = new Funcionarios();
        lstFuncionarios.add(f);
        
        int nLinhas = jTable1.getRowCount()-1;
        jTable1.setRowSelectionInterval(nLinhas, nLinhas);
        
        jTable1.requestFocus();
   
        
        
        
        
        
    }//GEN-LAST:event_jbadicionarActionPerformed
     // AQUI EU CRIEI UM BOTÃO EXCLUIR PARA PODER EXCLUIR UMA LINHA DA TABELA CASO O USUARIO DESEJA APAGAR UMA LINHA//
    private void jbexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexcluirActionPerformed
        // TODO add your handling code here:
        int selecionado = jTable1.getSelectedRow();
        lstFuncionarios.remove(selecionado);
        
        
        
       
    }//GEN-LAST:event_jbexcluirActionPerformed
        //AQUI EU FIZ COM QUE OS CAMPOS,jcargo, jsalario, jservico, jtsexo, jtqualificacao sÓ SERÃO ATIVADOS APOS UM CLICK NO BOTÃO NOVO//
    private void jbnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnovoActionPerformed
                    // TODO add your handling code here:
        jtcargo.setEnabled(true);
        jtsalario.setEnabled(true);
        jtservico.setEnabled(true);
        jtsexo.setEnabled(true);
        jtqualificacao.setEnabled(true);
        
        //E AQUI ATIVA TAMBÉM OS BOTÕES QUANDO SE CLIC NO BOTÃO "NOVO"
        jbadicionar.setEnabled(true);
        jblimpar.setEnabled(true);
        jbexcluir.setEnabled(true);
        jbsalvar.setEnabled(true);
        
    }//GEN-LAST:event_jbnovoActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded
    //AQUI QUANDO SE CLIC NO BOTÃO LIMPAR OS DADOS DOS CAMPOS SÃO LIMPOS//
    private void jblimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimparActionPerformed
        // TODO add your handling code here:
        jtcargo.setText("");
        jtsalario.setText("");
        jtsexo.setText("");
        jtservico.setText("");
        jtqualificacao.setText("");
        
        
        
    }//GEN-LAST:event_jblimparActionPerformed

    private void jtsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtsexoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtsexoActionPerformed
    // AQUI É O BOTÃO SLVAR DETERMINA QUE OS DADOS SÃO SALVOS DIRETAMENTE NO BANCO DE DADOS PGADMIN//
    private void jbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalvarActionPerformed

       if(jtcargo.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o campo cargo para continuar ");
           jtcargo.requestFocus();
       }else if (jtsexo.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o campo sexo para continuar ");
           jtsexo.requestFocus();
       }else if (jtservico.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o campo serviço para continuar");
           jtservico.requestFocus();
       }else if (jtsalario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o campo Salario para continuar");
           jtsalario.requestFocus();
       }else if (jtqualificacao.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o campo qualificação para continuar");
           jtqualificacao.requestFocus();
       }else
       mod.setCargo(jtcargo.getText());
       mod.setSexo(Integer.parseInt(jtsexo.getText()));
       mod.setServico(Integer.parseInt(jtservico.getText()));
       mod.setSalario(Double.parseDouble(jtsalario.getText()));
       mod.setQualificacao(Integer.parseInt(jtqualificacao.getText()));
       control.Salvar(mod);
       
       
        
        
    }//GEN-LAST:event_jbsalvarActionPerformed

    private void jtqualificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtqualificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtqualificacaoActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void formComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentRemoved

    private void jtcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcargoActionPerformed
        // AQUI EU LIMITEI A QUANTIDADE DE CARACTERE NO CAMPO TEMPO DE SERVICO ATÉ DOIS NUMEROS//
    private void jtservicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtservicoKeyTyped
        // TODO add your handling code here:
        if(jtservico.getText().length()>=2){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
       
    }//GEN-LAST:event_jtservicoKeyTyped
          // AQUI EU LIMITEI PARA O USUARIO INFORMAR NO CAMPO APENAS UM CARACTERE//
    private void jtsexoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtsexoKeyTyped
        // TODO add your handling code here:
        if(jtsexo.getText().length()>=1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
    }//GEN-LAST:event_jtsexoKeyTyped
        // AQUI EU LIMITEI PARA USUARIO INFORMAR ENTRE 0 OU 1 SE É OU NÃO QUALIFICADO//
    private void jtqualificacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtqualificacaoKeyTyped
        // TODO add your handling code here:
        if(jtqualificacao.getText().length()>=1){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jtqualificacaoKeyTyped

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTable1KeyTyped

    private void jtsexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtsexoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtsexoKeyPressed
       //AQUI EU LIMITEI PARA O USUARIO INFORMAR ENTRE 0 OU 1 E SE NO CASO DIGITAR OUTRA OPÇÃO O SISTEMA COLOCA 0 AUTOMATICAMENTE//
    private void jtsexoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtsexoKeyReleased
        // TODO add your handling code here:
        jtsexo.setText(jtsexo.getText().replaceAll("[^0-1]","0"));
    }//GEN-LAST:event_jtsexoKeyReleased

    private void jtqualificacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtqualificacaoKeyReleased
        //AQUI EU LIMITEI PARA O USUARIO INFORMAR ENTRE 0 OU 1 E SE NO CASO DIGITAR OUTRA OPÇÃO O SISTEMA COLOCA 0 AUTOMATICAMENTE//
        jtqualificacao.setText(jtqualificacao.getText().replaceAll("[^0-1]","0"));
    }//GEN-LAST:event_jtqualificacaoKeyReleased

    private void jtcargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtcargoKeyReleased
        // AQUI EU BLOQUEEI A ENTRADA DE NUMEROS SÓ ACEITANDO LETRAS PARA O CAMPO CARGO CASO INFORME NUMEROS NÃO SERA´PERMITIDO//
       jtcargo.setText(jtcargo.getText().replaceAll("[^aA-zZ-^-~-ç ]",""));
    }//GEN-LAST:event_jtcargoKeyReleased

    private void jtservicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtservicoKeyReleased
        // AQUI EU LIMITEI PAR O USUARIO INFORMAR APENAS NUMEROS CASO INFORME LETRAS NÃO SERÁ PERMITIDO//
    jtservico.setText(jtservico.getText().replaceAll("[^0-9]",""));
    }//GEN-LAST:event_jtservicoKeyReleased

    private void jtsalarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtsalarioKeyReleased
        // AQUI LIMITEI PARA O USUARIO INFORMAR APENAS NUMEROS CASO INFORME LETRAS NÃO SERA PERMITIDO//
    jtsalario.setText(jtsalario.getText().replaceAll("[^0-9]",""));
    }//GEN-LAST:event_jtsalarioKeyReleased
        // AQUI EU LIMITEI PAR ATÉ 7 CARACTERES NO CAMPO SALARIO PERMITINDO AO USUARIO INFORMAR ATÉ NA CASA DOS MILHOES SEU SALARIO KKK//
    private void jtsalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtsalarioKeyTyped
        // TODO add your handling code here:
    if(jtsalario.getText().length()>=7){
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_jtsalarioKeyTyped

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbadicionar;
    private javax.swing.JButton jbexcluir;
    private javax.swing.JButton jblimpar;
    private javax.swing.JButton jbnovo;
    private javax.swing.JButton jbsalvar;
    private javax.swing.JTextField jtcargo;
    private javax.swing.JTextField jtqualificacao;
    private javax.swing.JTextField jtsalario;
    private javax.swing.JTextField jtservico;
    private javax.swing.JTextField jtsexo;
    private java.util.List<Funcionarios> lstFuncionarios;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void setLocationnRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
